name: Smart Contracts CI

on:
  push:
    branches: [ "main", "master" ]
    # paths:
      # - 'smart-contracts/**'
  pull_request:
    branches: [ "main", "master" ]
    # paths:
      # - 'smart-contracts/**'

jobs:
  test:
    name: Run Hardhat Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./smart_contracts

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./smart_contracts/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile
        env:
          SEPOLIA_URL: "https://eth-sepolia.g.alchemy.com/v2/dummy"
          PRIVATE_KEY: "0x0000000000000000000000000000000000000000000000000000000000000000"

      - name: Run Tests
        run: npx hardhat test
        env:
          SEPOLIA_URL: "https://eth-sepolia.g.alchemy.com/v2/dummy"
          PRIVATE_KEY: "0x0000000000000000000000000000000000000000000000000000000000000000"
